### ISSUE TITLE
Add setting for font color

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/countdown#1]
Currently the background color can be modified but the color of the text is always teal.

**Comment by 96RadhikaJadhav** [comment]
@DenverCoder1 Could you please assign this issue to me as a part of hacktoberfest?

**Comment by DenverCoder1** [comment]
@96RadhikaJadhav 👍 Of course! Thanks!

**Comment by Shweta200126** [comment]
I know this got assigned but this is my first time and I would like to know how are we talking about change of colour?

permanently changing it to one? 

or does it change too with certain parameters.

**Comment by DenverCoder1** [comment]
@Shweta200126 To have a parameter in the url which will set the color and also an input in the create countdown form to allow people to choose the color.

**Comment by DenverCoder1** [comment]
@96RadhikaJadhav If you have any questions, I am happy to help

**Comment by Shweta200126** [comment]
I dont know where to find this link to the source with which @96RadhikaJadhav will do the assigned, its yours girl.

I just want to try !!
my first time too. 

can u link to the main code pls.thx.

**Comment by DenverCoder1** [comment]
@Shweta200126 Currently almost everything is in [index.php](https://github.com/DenverCoder1/countdown/blob/master/index.php). The form is in there as well as the accessing of url parameters.

**Comment by 96RadhikaJadhav** [comment]
Thanks @DenverCoder1 for assigning this to me! Will let you know once done.

**Comment by 96RadhikaJadhav** [comment]
@DenverCoder1  I'm facing some issue. I have done changes but font color input in the countdown is not getting added. Do I have to create separate function for font color as given for background one?

**Comment by DenverCoder1** [comment]
@96RadhikaJadhav The default font color is set line 23 of countdownStyle.css as `.cd p { ... color: #00796b; }`

To override that, you could put something at the bottom of the head, such as in the style where background and fonts are, but use an equal or more qualified selector. For example, you could do something like this in the head to overwrite the color.
```
.cd p {
    color: <?= $fontColor ?>;
}
```
Does that solve what you're asking about?

**Comment by 96RadhikaJadhav** [comment]
We have to add font color as an input to countdown also right? So when the countdown form will be displayed, there will be font color input also which we can change manually. Am I getting it right?

**Comment by DenverCoder1** [comment]
Sounds right.

We will need:

* Added input in the form for creating a countdown where a color can be inputted
* Adding the font color to the url as a parameter in the createCountdown function
* Retrieving the url parameter on the countdown page with PHP and using the value to color the text

**Comment by 96RadhikaJadhav** [comment]
Thanks for the explanation! As a first time contributor I have never done these many things. But I will give it a try.

**Comment by 96RadhikaJadhav** [comment]
@DenverCoder1 Could you please share me your mail?

**Comment by 96RadhikaJadhav** [comment]
Mail id*

**Comment by DenverCoder1** [comment]
@96RadhikaJadhav Feel free to message me if you have any questions
![image](https://user-images.githubusercontent.com/20955511/95323637-2ba92c80-08a7-11eb-8d2e-d86c00b31130.png)

**Comment by carlosfrontend** [comment]
This is my idea for sure that can be improved. Happy Coding!! :neckbeard:

**Comment by DenverCoder1** [comment]
Hi @carlosfrontend, thanks for working to contribute to open source. Please ask first, though, before doing work on an issue, especially one which has been assigned. @96RadhikaJadhav has already made the necessary changes a few days ago but has not yet been able to create the pull request.

**Comment by carlosfrontend** [comment]
Sorry I didn't know I was assigned. I saw this after sending pr ... Don't merge sent. Let's wait for @96RadhikaJadhav
