### ISSUE TITLE
Tooltips for filling out the form

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/countdown#13]
### Issue

Some input fields may need extra tips to help users figure out to correctly fill in the information.

For example, the UTC offset has a specific form for how it must be filled out (see issue #4)

Hint text like the following may be helpful:

![image](https://user-images.githubusercontent.com/20955511/95360284-d9cacb80-08d3-11eb-8829-b0ff1bcfd0a0.png)

The input boxes that accept hex codes could also have hint text.

You may choose how to word the hint text as long as it accurately describes what users should know about the input.

The tooltip should be next to the input box in a way where users will find it when filling out the form.

### References

https://www.w3schools.com/howto/howto_css_tooltip.asp

**Comment by zashton** [comment]
@DenverCoder1  Interested to help out, do assign issue to me  👍

**Comment by DenverCoder1** [comment]
@zashton Thanks, let me know if you need any help!
