### ISSUE TITLE
Fix font sizes when using <!DOCTYPE HTML>

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/countdown#22]
The change to add `<!DOCTYPE html>` (PR #18) caused some issues with the layout and font sizes.

Much of this seems to have to do with the use of inline styles.

To fix this issue:

* inline styles should be moved the countdownStyle.css file with appropriate class/id selectors
* `style` tags that are not in the `head` should be moved inside the `head`
* Adjust the font sizes and alignments in the CSS to make it look similar to (or better than) the first image below

These fixes should be made while keeping `<!DOCTYPE html>` in the code.

### Without `<!DOCTYPE html>`:

![image](https://user-images.githubusercontent.com/20955511/95683696-9cc54880-0bf5-11eb-89c2-8f54145a97f8.png)

### With `<!DOCTYPE html>`:

![image](https://user-images.githubusercontent.com/20955511/95683946-d5195680-0bf6-11eb-80ba-89fcf7621a40.png)

**Comment by Saul-BT** [comment]
Can I work on this issue?

**Comment by DenverCoder1** [comment]
@Saul-BT Yes, that would be great!
If you have any questions, don't hesitate to ask!

**Comment by djl218** [comment]
Did anyone offer to work on this yet?

**Comment by djl218** [comment]
Actually nevermind.  I have never used XAMPP before and am not familiar with php.  Sorry!

**Comment by DenverCoder1** [comment]
@djl218

> Did anyone offer to work on this yet?

I think someone asked but their comment seems to have been deleted.

> I have never used XAMPP before and am not familiar with php.

You could always learn something new! XAMPP is very simple to set up (there's a video linked about it). PHP adds the ability to run some code before the HTML appears and it can output some HTML. For this particular issue, you'd only need to make changes to the HTML/CSS parts of the file so you don't have to be familiar with PHP. Also I can answer any questions you might have.

Of course it's up to you to decide if you want to give a try, so don't feel pressured.

**Comment by djl218** [comment]
Good point!  I should learn something new.  I will do it then!  I should mention that I am trying to move to Denver, so it might be to my benefit to help out someone whose username is DenverCoder1 lol.

**Comment by djl218** [comment]
Im in!
http://prnt.sc/uxezl1
