### ISSUE TITLE
Adjustments to responsiveness for smaller screens

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/countdown#24]
On smaller screens, the text begins to overlap at certain screen sizes. This can be done in a few ways such as by using media rules (for example: `@media only screen and (max-width: 600px) {...}`) or by using clamp on font sizes (for example: `font-size: clamp(2rem, 22vw, 5rem);`).

There are already some media rules in countdownStyle.css which can be changed to work better on more screen sizes.

The layout should look good on all screen sizes which are greater than or equal to 320px wide.

More about media rules: https://www.w3schools.com/cssref/css3_pr_mediaquery.asp

More about clamp: https://developer.mozilla.org/en-US/docs/Web/CSS/clamp

### 740px (Looks fine)

![image](https://user-images.githubusercontent.com/20955511/95735465-823eae00-0c8d-11eb-97a2-f19adc6d22c0.png)

### 620px (Text is overlapping)

![image](https://user-images.githubusercontent.com/20955511/95735513-92568d80-0c8d-11eb-94d2-d03bb7d38637.png)

### 320px (Using mobile layout but text is still overlapping)

![image](https://user-images.githubusercontent.com/20955511/95735547-9edae600-0c8d-11eb-838d-d96a723de26b.png)

**Comment by BatoolMM** [comment]
Hi @DenverCoder1 , can you assign it to me, please?

**Comment by DenverCoder1** [comment]
@BatoolMM Sure, it's yours!
If you have any questions, don't hesitate to ask.

**Comment by ZsuzsaMano** [comment]
Does anybody work on this at the moment?
Would be great to assign a person to it.

**Comment by tharindulucky** [comment]
Guys I fixed the responsive issues on smaller screens and added a PR #25 
Let me know what you think.
