### ISSUE TITLE
Disallow input of text in the UTC offset input box for invalid characters

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/countdown#4]
UTC offset is always a number (ex. `-3.5`, `+0`, `+7`, etc.)

Currently it allows you to type any text in the input box.

Can we make it so that only characters that are: `+`, `-`, `.`, and digits will show up?

----

### **ISSUE A:**

`complete` Input validation has been added to make sure the input box in the countdown creation form contains a positive or negative floating point number

### **ISSUE B:**

`complete` Allow only valid offset values to be entered. That is, prevent values like +30:45 from being submitted.

### **ISSUE C:**

`complete` Apply validation from issues A and B to the "change timezone" input field on the countdown page.

Details:

* See how the UTC offset input box responds to input in the countdown form
* Implement changes to the text box that is create when changing the display timezone
* The text box for the user's preferred timezone appears when "Change Timezone" is clicked on a countdown page

![image](https://user-images.githubusercontent.com/20955511/95359003-55c41400-08d2-11eb-8e56-a00b07fcca8b.png)

----

Comment below to claim a part or all of this issue.

**Comment by hareesh-pillai** [comment]
Another related improvement could be to allow only valid offset values to be entered.
That is, prevent values like `+30:45` from being submitted.

**Comment by DenverCoder1** [comment]
Orginal suggestion has been solved with #10.

I will leave this open as @hareesh-pillai's suggested improvement can still be worked on.

**Comment by se98100** [comment]
I am working on it, I will do a PR as soon as I finish

**Comment by DenverCoder1** [comment]
Awesome! Thanks, @se98100.

**Comment by DenverCoder1** [comment]
One more related issue:

On the countdown page, you can click a button to change the displayed timezone.

This input field should have the same validation as the one in the countdown creation form.

**Comment by se98100** [comment]
@DenverCoder1 Do you want to keep the `.` notation or change to the `:` one?
For example `+12.75` would be `+12:45`, personally I'd prefer the second one but let me know!

**Comment by DenverCoder1** [comment]
@se98100 

The `:` notation looks good! It seems like the `:` notation is pretty common ([Wikipedia uses it](https://en.wikipedia.org/wiki/Template:UTC_time_offsets)). Without the 0's such as `+3` or `-4:30` should probably also work though.

Another idea could be to allow both notations and convert the format to `:` notation when it is saved.

I'll let you decide how you want to do it.

**Comment by se98100** [comment]
Today or tomorrow I will start working on issue C.

**Comment by DenverCoder1** [comment]
@se98100 Great!

**Comment by DenverCoder1** [comment]
Solved!
